//------------------------------------------------------------------------------
// <auto-generated>
//     Denna kod har genererats av ett verktyg.
//     Körtidsversion:4.0.30319.34014
//
//     Ändringar i denna fil kan orsaka fel och kommer att förloras om
//     koden återgenereras.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

public class AlwaysSingAI: MonoBehaviour, IAIBehaviour
{
	public Action GetAction(Unit unit)
	{
		return new Action(unit.Tile,null, null, this.GetComponent<Sing>(), null);
	}
}

