//------------------------------------------------------------------------------
// <auto-generated>
//     Denna kod har genererats av ett verktyg.
//     Körtidsversion:4.0.30319.34014
//
//     Ändringar i denna fil kan orsaka fel och kommer att förloras om
//     koden återgenereras.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;
using System;

public class Petrify : IEffect {

	public int Apply(DamageData attackData)
	{
		if (attackData.testAttack) return 10;
		return StaticApply(attackData);
	}

	static public int StaticApply(DamageData dd)
	{
		return StaticApply(dd.target.Tile, dd.source);
	}

	static public int StaticApply(Tile target, Unit user){
		if(target.Unit && target.Unit.IsAlive && target.Unit.GetComponent<Petrification>() == null)
			target.Unit.gameObject.AddComponent<Petrification>();
		else
			Debug.LogWarning("Tried to petrify an empty square!");
		return 25;
	}
}


