//------------------------------------------------------------------------------
// <auto-generated>
//     Denna kod har genererats av ett verktyg.
//     Körtidsversion:4.0.30319.34014
//
//     Ändringar i denna fil kan orsaka fel och kommer att förloras om
//     koden återgenereras.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

public class PetrifyAndDamage : MonoBehaviour, IEffect {
	
	static public int StaticApply(DamageData dd){
		if(!dd.testAttack) Petrify.StaticApply(dd);
		return Damage.StaticApply(dd); // may kill target, do last. Just to keep the sequence more safe.
	}

	public int Apply(DamageData attackData)
	{
		return StaticApply(attackData);
	}
}