//------------------------------------------------------------------------------
// <auto-generated>
//     Denna kod har genererats av ett verktyg.
//     Körtidsversion:4.0.30319.34014
//
//     Ändringar i denna fil kan orsaka fel och kommer att förloras om
//     koden återgenereras.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
public interface AIAbility
{
	float judgeAbility(Unit user, Tile move, out Tile target);
	Ability getAbility
	{
		get;
	}
	bool willCast();
}