//------------------------------------------------------------------------------
// <auto-generated>
//     Denna kod har genererats av ett verktyg.
//     Körtidsversion:4.0.30319.34014
//
//     Ändringar i denna fil kan orsaka fel och kommer att förloras om
//     koden återgenereras.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System;
using System.Collections.Generic;

public class Charm : AbilityWithManacost, TargetedAbility
{
	public override int ManaCost {
		get {
			return 2;
		}
	}

	public override string Name{
		get{
			return "Charm";
		}
	}

	public override void Use()
	{
		if(GetComponent<Mana>().CanCast(ManaCost)){
			TargetedAbilityInputManager.Instance.Listen(this);
		}else{
			OOM();
		}
	}

	public void Notify(Tile target)
	{
		target.Unit.team=2;
		target.Unit.gameObject.AddComponent<HeartSpawner>();
		FinishUse();
	}

	public HashSet<Tile> GetAvailableTargets()
	{
		Unit host = GetComponent<Unit>();
		
		HashSet<Tile> retVal=new HashSet<Tile>();
		if(host == null){
			Debug.LogError("host not found, is the charm ability sitting on a unit?");
			return retVal;
		}
		foreach(Tile t in RangeAndMelee.StaticGetTiles(host.Tile))
		{
			if(t.isOccuppied && host.isHostile(t.Unit)&&!t.Unit.invisible)
			{
				retVal.Add(t);
			}
		}
		return retVal;
	}

	public HashSet<Tile> GetAvailableTargets(Tile tile)
	{
		Unit host = GetComponent<Unit>();
		
		HashSet<Tile> retVal=new HashSet<Tile>();
		if(host == null){
			Debug.LogError("host not found, is the charm ability sitting on a unit?");
			return retVal;
		}
		foreach(Tile t in RangeAndMelee.StaticGetTiles(tile))
		{
			if(t.isOccuppied && host.isHostile(t.Unit)&&!t.Unit.invisible)
			{
				retVal.Add(t);
			}
		}
		return retVal;
	}

}

