//------------------------------------------------------------------------------
// <auto-generated>
//     Denna kod har genererats av ett verktyg.
//     Körtidsversion:4.0.30319.34014
//
//     Ändringar i denna fil kan orsaka fel och kommer att förloras om
//     koden återgenereras.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
public class DoubleAttack : Ability, Buff
{
	private Unit _unit;
	private Stats _buff;
	private bool _active = true;


	public override void Use ()
	{
		_active = !_active;
		_unit.doubleAttack = _active;
	}

	public override string Name{
		get{
			if(_active) return  "Single Strike!";
			return "Double Attack";
		}
	}
	
	void Start () 
	{
		_unit = GetComponent<Unit>();
		_unit.doubleAttack = true;
		BuffManager.Instance.Add(this);
		_buff = new Stats();
		_buff.baseAttackMod = -0.35f;
	}

	public bool Affects (Unit u)
	{
		return _active && u == _unit;
	}

	public Stats Stats {
		get {
			return _buff;
		}
	}

	void OnDestroy(){
		BuffManager.Instance.RemoveBuff(this);
	}
}
