//------------------------------------------------------------------------------
// <auto-generated>
//     Denna kod har genererats av ett verktyg.
//     Körtidsversion:4.0.30319.34014
//
//     Ändringar i denna fil kan orsaka fel och kommer att förloras om
//     koden återgenereras.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System;
using System.Collections.Generic;

public interface TargetedAbility
{
	void Notify(Tile target);
	HashSet<Tile> GetAvailableTargets();
	HashSet<Tile> GetAvailableTargets(Tile tile);
}