//------------------------------------------------------------------------------
//------------------------------------------------------------------------------
// <auto-generated>
//     Denna kod har genererats av ett verktyg.
//     Körtidsversion:4.0.30319.34014
//
//     Ändringar i denna fil kan orsaka fel och kommer att förloras om
//     koden återgenereras.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System;
using System.Collections.Generic;

public class Teleport : AbilityWithManacost, TargetedAbility
{
	public override int ManaCost {
		get {
			return 1;
		}
	}
	
	public override string Name
	{
		get
		{
			return "Teleport";
		}
	}
	
	public override void Use()
	{
		if(GetComponent<Mana>().CanCast(ManaCost)){
			TargetedAbilityInputManager.Instance.Listen(this);
		}else{
			OOM();
		}
	}
	
	public void Notify(Tile target)
	{
		GetComponent<Unit>().MoveTo(target);
		FinishUse();
	}
	
	public System.Collections.Generic.HashSet<Tile> GetAvailableTargets()
	{
		return TileGrid.Instance.GetFreeTiles();
	}

	public HashSet<Tile> GetAvailableTargets(Tile tile)
	{
		return TileGrid.Instance.GetFreeTiles();
	}
	
	
	
}

