//------------------------------------------------------------------------------
// <auto-generated>
//     Denna kod har genererats av ett verktyg.
//     Körtidsversion:4.0.30319.34014
//
//     Ändringar i denna fil kan orsaka fel och kommer att förloras om
//     koden återgenereras.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using UnityEngine;

public class EngageTargetEvent : MonoBehaviour
{
	public List<EventTarget> events;
	public bool enable=true;

	public void StartingAttackSequence()
	{
		Debug.Log("Attacked!");
		if (enable)
		{
			enable=false;
			triggerEvents();
		}

	}

	void triggerEvents()
	{
		foreach( EventTarget o in events)
		{
			o.Notice();
		}
	}
}

