//------------------------------------------------------------------------------
// <auto-generated>
//     Denna kod har genererats av ett verktyg.
//     Körtidsversion:4.0.30319.34014
//
//     Ändringar i denna fil kan orsaka fel och kommer att förloras om
//     koden återgenereras.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

public class RefillMana : EventTarget
{
	public override void Notice()
	{
		Tile targetTile = TileGrid.Instance.GetTileAt(transform.position);
		(targetTile.Unit.GetComponent<Mana>().ManaRemaining)++;

		Particle.Mana(transform.position);
		Destroy(gameObject);
	}
}