//------------------------------------------------------------------------------
// <auto-generated>
//     Denna kod har genererats av ett verktyg.
//     Körtidsversion:4.0.30319.34003
//
//     Ändringar i denna fil kan orsaka fel och kommer att förloras om
//     koden återgenereras.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
public class Action
{
	public Tile startTile;
	public Tile movement;
	public Tile attack;
	public Tile abilityTarget;
	public Ability ability;

	public Action (Tile startTile, Tile movement = null, Tile attack = null, Ability ability = null, Tile abilityTarget = null)
	{
		this.startTile = startTile;
		this.movement = movement;
		this.attack = attack;
		this.ability = ability;
		this.abilityTarget = abilityTarget;
	}

	public override string ToString ()
	{
		return string.Format ("[Action: startTile={0}, movement={1}, attack={2}]", startTile, movement, attack);
	}

	/// <summary>
	/// Gets a value indicating whether this instance is doing something.
	/// </summary>
	/// <value><c>true</c> if this instance is doing something; otherwise, <c>false</c>.</value>
	public bool IsDoingSomething{
		get{
			if(movement == null){
				if( attack == null)
				{
					return ability!=null;
				}
			}
			return true;
		}
	}
}

