//------------------------------------------------------------------------------
// <auto-generated>
//     Denna kod har genererats av ett verktyg.
//     Körtidsversion:4.0.30319.34014
//
//     Ändringar i denna fil kan orsaka fel och kommer att förloras om
//     koden återgenereras.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System;

public class EmptyAbility : Ability
{
	public override string Name
	{
		get
		{
			return "Empty Ability";
		}
	}

	public override void Use()
	{
		Debug.Log("Did fancy stuffs");
	}


}


